///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MPNS_TEST.Repositorys.infomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the infomation014 element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("4737d2f4-8312-4ea9-92e1-ab917cfe1774")]
    public partial class infomation014 : RepoGenBaseFolder
    {
        static infomation014 instance = new infomation014();
        infomation014Folders.维护AppFolder _维护;
        infomation014Folders.筛查信息AppFolder _筛查信息;

        /// <summary>
        /// Gets the singleton class instance representing the infomation014 element repository.
        /// </summary>
        [RepositoryFolder("4737d2f4-8312-4ea9-92e1-ab917cfe1774")]
        public static infomation014 Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public infomation014() 
            : base("infomation014", "/", null, 0, false, "4737d2f4-8312-4ea9-92e1-ab917cfe1774", ".\\RepositoryImages\\infomation0144737d2f4.rximgres")
        {
            _维护 = new infomation014Folders.维护AppFolder(this);
            _筛查信息 = new infomation014Folders.筛查信息AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4737d2f4-8312-4ea9-92e1-ab917cfe1774")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The 维护 folder.
        /// </summary>
        [RepositoryFolder("fa434f56-77c5-493d-9268-222427114ccc")]
        public virtual infomation014Folders.维护AppFolder 维护
        {
            get { return _维护; }
        }

        /// <summary>
        /// The 筛查信息 folder.
        /// </summary>
        [RepositoryFolder("a7efca04-702f-438e-be5f-6859c2578b63")]
        public virtual infomation014Folders.筛查信息AppFolder 筛查信息
        {
            get { return _筛查信息; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class infomation014Folders
    {
        /// <summary>
        /// The 维护AppFolder folder.
        /// </summary>
        [RepositoryFolder("fa434f56-77c5-493d-9268-222427114ccc")]
        public partial class 维护AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _维护管理Info;
            RepoItemInfo _参数信息Info;
            RepoItemInfo _筛查号前缀Info;
            RepoItemInfo _自增筛查号位数Info;
            RepoItemInfo _保存Info;

            /// <summary>
            /// Creates a new 维护  folder.
            /// </summary>
            public 维护AppFolder(RepoGenBaseFolder parentFolder) :
                    base("维护", "/dom[@domain='localhost:8016']", parentFolder, 30000, null, false, "fa434f56-77c5-493d-9268-222427114ccc", "")
            {
                _维护管理Info = new RepoItemInfo(this, "维护管理", ".//ul[#'mainmenus']/?/?/a[@innertext='维护管理']", 30000, null, "af14041f-7766-4a37-a935-58a8d72444fc");
                _参数信息Info = new RepoItemInfo(this, "参数信息", ".//ul[#'mainmenus']/li[5]/div/ul/?/?/a[@innertext='参数信息']", 30000, null, "92af5527-5c64-4f52-9272-62cc937457ed");
                _筛查号前缀Info = new RepoItemInfo(this, "筛查号前缀", ".//input[#'CheckNoHeadString']", 30000, null, "85eb80d0-0efa-4939-8ebc-aa421ca0671d");
                _自增筛查号位数Info = new RepoItemInfo(this, "自增筛查号位数", ".//input[#'CheckNoLen']", 30000, null, "55a2af4e-747c-4844-b1ad-ab41b5e28bdb");
                _保存Info = new RepoItemInfo(this, "保存", ".//input[#'but_EntrySetting']", 30000, null, "80039e9a-870f-4726-a859-efa9aab6291e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fa434f56-77c5-493d-9268-222427114ccc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fa434f56-77c5-493d-9268-222427114ccc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The 维护管理 item.
            /// </summary>
            [RepositoryItem("af14041f-7766-4a37-a935-58a8d72444fc")]
            public virtual Ranorex.ATag 维护管理
            {
                get
                {
                    return _维护管理Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The 维护管理 item info.
            /// </summary>
            [RepositoryItemInfo("af14041f-7766-4a37-a935-58a8d72444fc")]
            public virtual RepoItemInfo 维护管理Info
            {
                get
                {
                    return _维护管理Info;
                }
            }

            /// <summary>
            /// The 参数信息 item.
            /// </summary>
            [RepositoryItem("92af5527-5c64-4f52-9272-62cc937457ed")]
            public virtual Ranorex.ATag 参数信息
            {
                get
                {
                    return _参数信息Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The 参数信息 item info.
            /// </summary>
            [RepositoryItemInfo("92af5527-5c64-4f52-9272-62cc937457ed")]
            public virtual RepoItemInfo 参数信息Info
            {
                get
                {
                    return _参数信息Info;
                }
            }

            /// <summary>
            /// The 筛查号前缀 item.
            /// </summary>
            [RepositoryItem("85eb80d0-0efa-4939-8ebc-aa421ca0671d")]
            public virtual Ranorex.InputTag 筛查号前缀
            {
                get
                {
                    return _筛查号前缀Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 筛查号前缀 item info.
            /// </summary>
            [RepositoryItemInfo("85eb80d0-0efa-4939-8ebc-aa421ca0671d")]
            public virtual RepoItemInfo 筛查号前缀Info
            {
                get
                {
                    return _筛查号前缀Info;
                }
            }

            /// <summary>
            /// The 自增筛查号位数 item.
            /// </summary>
            [RepositoryItem("55a2af4e-747c-4844-b1ad-ab41b5e28bdb")]
            public virtual Ranorex.InputTag 自增筛查号位数
            {
                get
                {
                    return _自增筛查号位数Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 自增筛查号位数 item info.
            /// </summary>
            [RepositoryItemInfo("55a2af4e-747c-4844-b1ad-ab41b5e28bdb")]
            public virtual RepoItemInfo 自增筛查号位数Info
            {
                get
                {
                    return _自增筛查号位数Info;
                }
            }

            /// <summary>
            /// The 保存 item.
            /// </summary>
            [RepositoryItem("80039e9a-870f-4726-a859-efa9aab6291e")]
            public virtual Ranorex.InputTag 保存
            {
                get
                {
                    return _保存Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 保存 item info.
            /// </summary>
            [RepositoryItemInfo("80039e9a-870f-4726-a859-efa9aab6291e")]
            public virtual RepoItemInfo 保存Info
            {
                get
                {
                    return _保存Info;
                }
            }
        }

        /// <summary>
        /// The 筛查信息AppFolder folder.
        /// </summary>
        [RepositoryFolder("a7efca04-702f-438e-be5f-6859c2578b63")]
        public partial class 筛查信息AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _筛查管理Info;
            RepoItemInfo _筛查信息Info;
            RepoItemInfo _筛查号Info;
            RepoItemInfo _孕妇姓名Info;
            RepoItemInfo _出生日期Info;
            RepoItemInfo _保存按钮Info;
            RepoItemInfo _保存失败确定Info;
            RepoItemInfo _社保卡保存失败确定Info;

            /// <summary>
            /// Creates a new 筛查信息  folder.
            /// </summary>
            public 筛查信息AppFolder(RepoGenBaseFolder parentFolder) :
                    base("筛查信息", "/dom[@domain='localhost:8016']", parentFolder, 30000, null, false, "a7efca04-702f-438e-be5f-6859c2578b63", "")
            {
                _筛查管理Info = new RepoItemInfo(this, "筛查管理", ".//ul[#'mainmenus']/?/?/a[@innertext='筛查管理']", 30000, null, "f6984859-bfde-4674-9e61-c1cb3a259c66");
                _筛查信息Info = new RepoItemInfo(this, "筛查信息", ".//ul[#'mainmenus']/?/?/div/ul/?/?/a[@innertext='筛查信息']", 30000, null, "e453ddd0-0b7e-4c8c-9961-38eb0cd79378");
                _筛查号Info = new RepoItemInfo(this, "筛查号", ".//input[#'CheckNo']", 30000, null, "e3a9d696-d3cb-418d-ac11-8ecc39fc115d");
                _孕妇姓名Info = new RepoItemInfo(this, "孕妇姓名", ".//input[#'FirstName']", 30000, null, "939bc867-274b-46b3-9c80-06e123668baf");
                _出生日期Info = new RepoItemInfo(this, "出生日期", ".//input[#'BirthDate']", 30000, null, "a8333816-9850-4ae0-b189-8570117a8500");
                _保存按钮Info = new RepoItemInfo(this, "保存按钮", ".//input[#'butSavePregnant']", 30000, null, "14b19b0d-0aaf-464c-954c-cb16168186d7");
                _保存失败确定Info = new RepoItemInfo(this, "保存失败确定", ".//div[#'xubox_layer3']//a[@innertext='确定']", 30000, null, "667c4daa-cae9-4f35-b552-517de4926614");
                _社保卡保存失败确定Info = new RepoItemInfo(this, "社保卡保存失败确定", ".//div[#'xubox_layer1']//a[@innertext='确定']", 30000, null, "c940f0e2-dd00-4a68-8dcc-92ed29b2817b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a7efca04-702f-438e-be5f-6859c2578b63")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a7efca04-702f-438e-be5f-6859c2578b63")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The 筛查管理 item.
            /// </summary>
            [RepositoryItem("f6984859-bfde-4674-9e61-c1cb3a259c66")]
            public virtual Ranorex.ATag 筛查管理
            {
                get
                {
                    return _筛查管理Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The 筛查管理 item info.
            /// </summary>
            [RepositoryItemInfo("f6984859-bfde-4674-9e61-c1cb3a259c66")]
            public virtual RepoItemInfo 筛查管理Info
            {
                get
                {
                    return _筛查管理Info;
                }
            }

            /// <summary>
            /// The 筛查信息 item.
            /// </summary>
            [RepositoryItem("e453ddd0-0b7e-4c8c-9961-38eb0cd79378")]
            public virtual Ranorex.ATag 筛查信息
            {
                get
                {
                    return _筛查信息Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The 筛查信息 item info.
            /// </summary>
            [RepositoryItemInfo("e453ddd0-0b7e-4c8c-9961-38eb0cd79378")]
            public virtual RepoItemInfo 筛查信息Info
            {
                get
                {
                    return _筛查信息Info;
                }
            }

            /// <summary>
            /// The 筛查号 item.
            /// </summary>
            [RepositoryItem("e3a9d696-d3cb-418d-ac11-8ecc39fc115d")]
            public virtual Ranorex.InputTag 筛查号
            {
                get
                {
                    return _筛查号Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 筛查号 item info.
            /// </summary>
            [RepositoryItemInfo("e3a9d696-d3cb-418d-ac11-8ecc39fc115d")]
            public virtual RepoItemInfo 筛查号Info
            {
                get
                {
                    return _筛查号Info;
                }
            }

            /// <summary>
            /// The 孕妇姓名 item.
            /// </summary>
            [RepositoryItem("939bc867-274b-46b3-9c80-06e123668baf")]
            public virtual Ranorex.InputTag 孕妇姓名
            {
                get
                {
                    return _孕妇姓名Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 孕妇姓名 item info.
            /// </summary>
            [RepositoryItemInfo("939bc867-274b-46b3-9c80-06e123668baf")]
            public virtual RepoItemInfo 孕妇姓名Info
            {
                get
                {
                    return _孕妇姓名Info;
                }
            }

            /// <summary>
            /// The 出生日期 item.
            /// </summary>
            [RepositoryItem("a8333816-9850-4ae0-b189-8570117a8500")]
            public virtual Ranorex.InputTag 出生日期
            {
                get
                {
                    return _出生日期Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 出生日期 item info.
            /// </summary>
            [RepositoryItemInfo("a8333816-9850-4ae0-b189-8570117a8500")]
            public virtual RepoItemInfo 出生日期Info
            {
                get
                {
                    return _出生日期Info;
                }
            }

            /// <summary>
            /// The 保存按钮 item.
            /// </summary>
            [RepositoryItem("14b19b0d-0aaf-464c-954c-cb16168186d7")]
            public virtual Ranorex.InputTag 保存按钮
            {
                get
                {
                    return _保存按钮Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 保存按钮 item info.
            /// </summary>
            [RepositoryItemInfo("14b19b0d-0aaf-464c-954c-cb16168186d7")]
            public virtual RepoItemInfo 保存按钮Info
            {
                get
                {
                    return _保存按钮Info;
                }
            }

            /// <summary>
            /// The 保存失败确定 item.
            /// </summary>
            [RepositoryItem("667c4daa-cae9-4f35-b552-517de4926614")]
            public virtual Ranorex.ATag 保存失败确定
            {
                get
                {
                    return _保存失败确定Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The 保存失败确定 item info.
            /// </summary>
            [RepositoryItemInfo("667c4daa-cae9-4f35-b552-517de4926614")]
            public virtual RepoItemInfo 保存失败确定Info
            {
                get
                {
                    return _保存失败确定Info;
                }
            }

            /// <summary>
            /// The 社保卡保存失败确定 item.
            /// </summary>
            [RepositoryItem("c940f0e2-dd00-4a68-8dcc-92ed29b2817b")]
            public virtual Ranorex.ATag 社保卡保存失败确定
            {
                get
                {
                    return _社保卡保存失败确定Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The 社保卡保存失败确定 item info.
            /// </summary>
            [RepositoryItemInfo("c940f0e2-dd00-4a68-8dcc-92ed29b2817b")]
            public virtual RepoItemInfo 社保卡保存失败确定Info
            {
                get
                {
                    return _社保卡保存失败确定Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
