///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MPNS_TEST.Repositorys.infomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the infomation021 element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ad464cbe-ae24-4ca7-a37a-5a8242d90bf6")]
    public partial class infomation021 : RepoGenBaseFolder
    {
        static infomation021 instance = new infomation021();
        infomation021Folders.筛查信息AppFolder _筛查信息;
        infomation021Folders.中期样本AppFolder _中期样本;

        /// <summary>
        /// Gets the singleton class instance representing the infomation021 element repository.
        /// </summary>
        [RepositoryFolder("ad464cbe-ae24-4ca7-a37a-5a8242d90bf6")]
        public static infomation021 Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public infomation021() 
            : base("infomation021", "/", null, 0, false, "ad464cbe-ae24-4ca7-a37a-5a8242d90bf6", ".\\RepositoryImages\\infomation021ad464cbe.rximgres")
        {
            _筛查信息 = new infomation021Folders.筛查信息AppFolder(this);
            _中期样本 = new infomation021Folders.中期样本AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ad464cbe-ae24-4ca7-a37a-5a8242d90bf6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The 筛查信息 folder.
        /// </summary>
        [RepositoryFolder("a7efca04-702f-438e-be5f-6859c2578b63")]
        public virtual infomation021Folders.筛查信息AppFolder 筛查信息
        {
            get { return _筛查信息; }
        }

        /// <summary>
        /// The 中期样本 folder.
        /// </summary>
        [RepositoryFolder("44ab4b90-bee2-4097-9b7b-e47d66e7008a")]
        public virtual infomation021Folders.中期样本AppFolder 中期样本
        {
            get { return _中期样本; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class infomation021Folders
    {
        /// <summary>
        /// The 筛查信息AppFolder folder.
        /// </summary>
        [RepositoryFolder("a7efca04-702f-438e-be5f-6859c2578b63")]
        public partial class 筛查信息AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _筛查管理Info;
            RepoItemInfo _筛查信息Info;
            RepoItemInfo _筛查号Info;
            RepoItemInfo _孕妇姓名Info;
            RepoItemInfo _病历号Info;
            RepoItemInfo _登记日期Info;
            RepoItemInfo _出生日期Info;
            RepoItemInfo _保存按钮Info;

            /// <summary>
            /// Creates a new 筛查信息  folder.
            /// </summary>
            public 筛查信息AppFolder(RepoGenBaseFolder parentFolder) :
                    base("筛查信息", "/dom[@domain='localhost:8016']", parentFolder, 30000, null, false, "a7efca04-702f-438e-be5f-6859c2578b63", "")
            {
                _筛查管理Info = new RepoItemInfo(this, "筛查管理", ".//ul[#'mainmenus']/?/?/a[@innertext='筛查管理']", 30000, null, "f6984859-bfde-4674-9e61-c1cb3a259c66");
                _筛查信息Info = new RepoItemInfo(this, "筛查信息", ".//ul[#'mainmenus']/?/?/div/ul/?/?/a[@innertext='筛查信息']", 30000, null, "e453ddd0-0b7e-4c8c-9961-38eb0cd79378");
                _筛查号Info = new RepoItemInfo(this, "筛查号", ".//input[#'CheckNo']", 30000, null, "892fd28f-38d4-4223-a1e1-35f01dec6616");
                _孕妇姓名Info = new RepoItemInfo(this, "孕妇姓名", ".//input[#'FirstName']", 30000, null, "939bc867-274b-46b3-9c80-06e123668baf");
                _病历号Info = new RepoItemInfo(this, "病历号", ".//input[#'PatientID']", 30000, null, "7f2d4a54-739b-4331-af9e-e2fba5beecc9");
                _登记日期Info = new RepoItemInfo(this, "登记日期", ".//input[#'RegisterDate']", 30000, null, "33b2596d-a7b2-4220-96a3-a1c4828d28fb");
                _出生日期Info = new RepoItemInfo(this, "出生日期", ".//input[#'BirthDate']", 30000, null, "a8333816-9850-4ae0-b189-8570117a8500");
                _保存按钮Info = new RepoItemInfo(this, "保存按钮", ".//input[#'butSavePregnant']", 30000, null, "14b19b0d-0aaf-464c-954c-cb16168186d7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a7efca04-702f-438e-be5f-6859c2578b63")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a7efca04-702f-438e-be5f-6859c2578b63")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The 筛查管理 item.
            /// </summary>
            [RepositoryItem("f6984859-bfde-4674-9e61-c1cb3a259c66")]
            public virtual Ranorex.ATag 筛查管理
            {
                get
                {
                    return _筛查管理Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The 筛查管理 item info.
            /// </summary>
            [RepositoryItemInfo("f6984859-bfde-4674-9e61-c1cb3a259c66")]
            public virtual RepoItemInfo 筛查管理Info
            {
                get
                {
                    return _筛查管理Info;
                }
            }

            /// <summary>
            /// The 筛查信息 item.
            /// </summary>
            [RepositoryItem("e453ddd0-0b7e-4c8c-9961-38eb0cd79378")]
            public virtual Ranorex.ATag 筛查信息
            {
                get
                {
                    return _筛查信息Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The 筛查信息 item info.
            /// </summary>
            [RepositoryItemInfo("e453ddd0-0b7e-4c8c-9961-38eb0cd79378")]
            public virtual RepoItemInfo 筛查信息Info
            {
                get
                {
                    return _筛查信息Info;
                }
            }

            /// <summary>
            /// The 筛查号 item.
            /// </summary>
            [RepositoryItem("892fd28f-38d4-4223-a1e1-35f01dec6616")]
            public virtual Ranorex.InputTag 筛查号
            {
                get
                {
                    return _筛查号Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 筛查号 item info.
            /// </summary>
            [RepositoryItemInfo("892fd28f-38d4-4223-a1e1-35f01dec6616")]
            public virtual RepoItemInfo 筛查号Info
            {
                get
                {
                    return _筛查号Info;
                }
            }

            /// <summary>
            /// The 孕妇姓名 item.
            /// </summary>
            [RepositoryItem("939bc867-274b-46b3-9c80-06e123668baf")]
            public virtual Ranorex.InputTag 孕妇姓名
            {
                get
                {
                    return _孕妇姓名Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 孕妇姓名 item info.
            /// </summary>
            [RepositoryItemInfo("939bc867-274b-46b3-9c80-06e123668baf")]
            public virtual RepoItemInfo 孕妇姓名Info
            {
                get
                {
                    return _孕妇姓名Info;
                }
            }

            /// <summary>
            /// The 病历号 item.
            /// </summary>
            [RepositoryItem("7f2d4a54-739b-4331-af9e-e2fba5beecc9")]
            public virtual Ranorex.InputTag 病历号
            {
                get
                {
                    return _病历号Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 病历号 item info.
            /// </summary>
            [RepositoryItemInfo("7f2d4a54-739b-4331-af9e-e2fba5beecc9")]
            public virtual RepoItemInfo 病历号Info
            {
                get
                {
                    return _病历号Info;
                }
            }

            /// <summary>
            /// The 登记日期 item.
            /// </summary>
            [RepositoryItem("33b2596d-a7b2-4220-96a3-a1c4828d28fb")]
            public virtual Ranorex.InputTag 登记日期
            {
                get
                {
                    return _登记日期Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 登记日期 item info.
            /// </summary>
            [RepositoryItemInfo("33b2596d-a7b2-4220-96a3-a1c4828d28fb")]
            public virtual RepoItemInfo 登记日期Info
            {
                get
                {
                    return _登记日期Info;
                }
            }

            /// <summary>
            /// The 出生日期 item.
            /// </summary>
            [RepositoryItem("a8333816-9850-4ae0-b189-8570117a8500")]
            public virtual Ranorex.InputTag 出生日期
            {
                get
                {
                    return _出生日期Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 出生日期 item info.
            /// </summary>
            [RepositoryItemInfo("a8333816-9850-4ae0-b189-8570117a8500")]
            public virtual RepoItemInfo 出生日期Info
            {
                get
                {
                    return _出生日期Info;
                }
            }

            /// <summary>
            /// The 保存按钮 item.
            /// </summary>
            [RepositoryItem("14b19b0d-0aaf-464c-954c-cb16168186d7")]
            public virtual Ranorex.InputTag 保存按钮
            {
                get
                {
                    return _保存按钮Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 保存按钮 item info.
            /// </summary>
            [RepositoryItemInfo("14b19b0d-0aaf-464c-954c-cb16168186d7")]
            public virtual RepoItemInfo 保存按钮Info
            {
                get
                {
                    return _保存按钮Info;
                }
            }
        }

        /// <summary>
        /// The 中期样本AppFolder folder.
        /// </summary>
        [RepositoryFolder("44ab4b90-bee2-4097-9b7b-e47d66e7008a")]
        public partial class 中期样本AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _新增中期样本Info;
            RepoItemInfo _中期样本号Info;
            RepoItemInfo _体重Info;
            RepoItemInfo _孕周类型Info;
            RepoItemInfo _评估孕周周Info;
            RepoItemInfo _评估孕周天Info;
            RepoItemInfo _计算Info;
            RepoItemInfo _保存按钮Info;
            RepoItemInfo _搜索框Info;
            RepoItemInfo _左侧Info;

            /// <summary>
            /// Creates a new 中期样本  folder.
            /// </summary>
            public 中期样本AppFolder(RepoGenBaseFolder parentFolder) :
                    base("中期样本", "/dom[@domain='localhost:8016']", parentFolder, 30000, null, false, "44ab4b90-bee2-4097-9b7b-e47d66e7008a", "")
            {
                _新增中期样本Info = new RepoItemInfo(this, "新增中期样本", ".//input[#'butInsertMiddleSample']", 30000, null, "54ce9aab-cea9-4144-9bf6-c94d1914a37b");
                _中期样本号Info = new RepoItemInfo(this, "中期样本号", ".//div[#'sampleinfoandtestinfomiddle_list']/?/?/table/tbody/tr[2]/?/?/input[@name='ed6481ba-ff48-45dc-a811-95903450600e|SampleID']", 30000, null, "e240d6d2-0a8b-402d-a4e1-dd6efe080b1b");
                _体重Info = new RepoItemInfo(this, "体重", ".//div[#'sampleinfoandtestinfomiddle_list']/?/?/table//td[@innertext=' (Kg) ']/input[@name='ed6481ba-ff48-45dc-a811-95903450600e|Weight']", 30000, null, "d4adddde-7ee8-4e4b-a182-895b225c540a");
                _孕周类型Info = new RepoItemInfo(this, "孕周类型", ".//div[#'sampleinfoandtestinfomiddle_list']/?/?/table/tbody/tr[9]/?/?/table/tbody/tr[1]/?/?/select[@name='ed6481ba-ff48-45dc-a811-95903450600e|GestationType']", 30000, null, "59d16259-c099-4ce9-80ef-dcdd46a17aef");
                _评估孕周周Info = new RepoItemInfo(this, "评估孕周周", ".//div[#'sampleinfoandtestinfomiddle_list']/?/?/table/tbody/tr[9]/?/?/table//td[@innertext=' 周  天']/input[@name='ed6481ba-ff48-45dc-a811-95903450600e|GestationWeek']", 30000, null, "c27fe81c-dcad-4c27-a117-c01164e4a5ca");
                _评估孕周天Info = new RepoItemInfo(this, "评估孕周天", ".//div[#'sampleinfoandtestinfomiddle_list']/?/?/table/tbody/tr[9]/?/?/table//td[@innertext=' 周  天']/input[@name='ed6481ba-ff48-45dc-a811-95903450600e|GestationDay']", 30000, null, "5af2cd66-103a-48f7-93b3-eb9ab74014b1");
                _计算Info = new RepoItemInfo(this, "计算", ".//div[#'sampleinfoandtestinfomiddle_list']/?/?/table/tbody/tr[10]//input[@type='button']", 30000, null, "dd9a9735-1443-44bd-8f73-b8432d0b0301");
                _保存按钮Info = new RepoItemInfo(this, "保存按钮", ".//div[#'sampleinfoandtestinfomiddle_list']/?/?/table/tbody/tr[10]//input[@name='ed6481ba-ff48-45dc-a811-95903450600e_butSaveSample']", 30000, null, "b21e69d7-7a42-41a9-94a9-c93868f4e054");
                _搜索框Info = new RepoItemInfo(this, "搜索框", ".//input[#'txt_searchKeys']", 30000, null, "d4ee2f26-0ce9-4df9-84d1-0a6c89b25092");
                _左侧Info = new RepoItemInfo(this, "左侧", "body/div[2]/div[2]/table[2]/?/?/tr/td[1]/div[1]", 30000, null, "ef440cf7-9c78-4d55-bcce-aaae14d3068c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("44ab4b90-bee2-4097-9b7b-e47d66e7008a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("44ab4b90-bee2-4097-9b7b-e47d66e7008a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The 新增中期样本 item.
            /// </summary>
            [RepositoryItem("54ce9aab-cea9-4144-9bf6-c94d1914a37b")]
            public virtual Ranorex.InputTag 新增中期样本
            {
                get
                {
                    return _新增中期样本Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 新增中期样本 item info.
            /// </summary>
            [RepositoryItemInfo("54ce9aab-cea9-4144-9bf6-c94d1914a37b")]
            public virtual RepoItemInfo 新增中期样本Info
            {
                get
                {
                    return _新增中期样本Info;
                }
            }

            /// <summary>
            /// The 中期样本号 item.
            /// </summary>
            [RepositoryItem("e240d6d2-0a8b-402d-a4e1-dd6efe080b1b")]
            public virtual Ranorex.InputTag 中期样本号
            {
                get
                {
                    return _中期样本号Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 中期样本号 item info.
            /// </summary>
            [RepositoryItemInfo("e240d6d2-0a8b-402d-a4e1-dd6efe080b1b")]
            public virtual RepoItemInfo 中期样本号Info
            {
                get
                {
                    return _中期样本号Info;
                }
            }

            /// <summary>
            /// The 体重 item.
            /// </summary>
            [RepositoryItem("d4adddde-7ee8-4e4b-a182-895b225c540a")]
            public virtual Ranorex.InputTag 体重
            {
                get
                {
                    return _体重Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 体重 item info.
            /// </summary>
            [RepositoryItemInfo("d4adddde-7ee8-4e4b-a182-895b225c540a")]
            public virtual RepoItemInfo 体重Info
            {
                get
                {
                    return _体重Info;
                }
            }

            /// <summary>
            /// The 孕周类型 item.
            /// </summary>
            [RepositoryItem("59d16259-c099-4ce9-80ef-dcdd46a17aef")]
            public virtual Ranorex.SelectTag 孕周类型
            {
                get
                {
                    return _孕周类型Info.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The 孕周类型 item info.
            /// </summary>
            [RepositoryItemInfo("59d16259-c099-4ce9-80ef-dcdd46a17aef")]
            public virtual RepoItemInfo 孕周类型Info
            {
                get
                {
                    return _孕周类型Info;
                }
            }

            /// <summary>
            /// The 评估孕周周 item.
            /// </summary>
            [RepositoryItem("c27fe81c-dcad-4c27-a117-c01164e4a5ca")]
            public virtual Ranorex.InputTag 评估孕周周
            {
                get
                {
                    return _评估孕周周Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 评估孕周周 item info.
            /// </summary>
            [RepositoryItemInfo("c27fe81c-dcad-4c27-a117-c01164e4a5ca")]
            public virtual RepoItemInfo 评估孕周周Info
            {
                get
                {
                    return _评估孕周周Info;
                }
            }

            /// <summary>
            /// The 评估孕周天 item.
            /// </summary>
            [RepositoryItem("5af2cd66-103a-48f7-93b3-eb9ab74014b1")]
            public virtual Ranorex.InputTag 评估孕周天
            {
                get
                {
                    return _评估孕周天Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 评估孕周天 item info.
            /// </summary>
            [RepositoryItemInfo("5af2cd66-103a-48f7-93b3-eb9ab74014b1")]
            public virtual RepoItemInfo 评估孕周天Info
            {
                get
                {
                    return _评估孕周天Info;
                }
            }

            /// <summary>
            /// The 计算 item.
            /// </summary>
            [RepositoryItem("dd9a9735-1443-44bd-8f73-b8432d0b0301")]
            public virtual Ranorex.InputTag 计算
            {
                get
                {
                    return _计算Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 计算 item info.
            /// </summary>
            [RepositoryItemInfo("dd9a9735-1443-44bd-8f73-b8432d0b0301")]
            public virtual RepoItemInfo 计算Info
            {
                get
                {
                    return _计算Info;
                }
            }

            /// <summary>
            /// The 保存按钮 item.
            /// </summary>
            [RepositoryItem("b21e69d7-7a42-41a9-94a9-c93868f4e054")]
            public virtual Ranorex.InputTag 保存按钮
            {
                get
                {
                    return _保存按钮Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 保存按钮 item info.
            /// </summary>
            [RepositoryItemInfo("b21e69d7-7a42-41a9-94a9-c93868f4e054")]
            public virtual RepoItemInfo 保存按钮Info
            {
                get
                {
                    return _保存按钮Info;
                }
            }

            /// <summary>
            /// The 搜索框 item.
            /// </summary>
            [RepositoryItem("d4ee2f26-0ce9-4df9-84d1-0a6c89b25092")]
            public virtual Ranorex.InputTag 搜索框
            {
                get
                {
                    return _搜索框Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The 搜索框 item info.
            /// </summary>
            [RepositoryItemInfo("d4ee2f26-0ce9-4df9-84d1-0a6c89b25092")]
            public virtual RepoItemInfo 搜索框Info
            {
                get
                {
                    return _搜索框Info;
                }
            }

            /// <summary>
            /// The 左侧 item.
            /// </summary>
            [RepositoryItem("ef440cf7-9c78-4d55-bcce-aaae14d3068c")]
            public virtual Ranorex.DivTag 左侧
            {
                get
                {
                    return _左侧Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The 左侧 item info.
            /// </summary>
            [RepositoryItemInfo("ef440cf7-9c78-4d55-bcce-aaae14d3068c")]
            public virtual RepoItemInfo 左侧Info
            {
                get
                {
                    return _左侧Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
