///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MPNS_TEST.Models.Screening_Management.pregnant
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The pregnant002 recording.
    /// </summary>
    [TestModule("e69cf533-cc6a-48df-b1bf-84cf3db55a68", ModuleType.Recording, 1)]
    public partial class pregnant002 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MPNS_TEST.Repositorys.Infomation repository.
        /// </summary>
        public static global::MPNS_TEST.Repositorys.Infomation repo = global::MPNS_TEST.Repositorys.Infomation.Instance;

        static pregnant002 instance = new pregnant002();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public pregnant002()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static pregnant002 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.筛查管理' at Center.", repo.页面头选择.筛查管理Info, new RecordItemIndex(0));
            repo.页面头选择.筛查管理.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.孕妇信息' at Center.", repo.页面头选择.孕妇信息Info, new RecordItemIndex(1));
            repo.页面头选择.孕妇信息.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(2));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '孕妇信息.高级查询' at Center.", repo.孕妇信息.高级查询Info, new RecordItemIndex(3));
            repo.孕妇信息.高级查询.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to 'BLH00001' on item '孕妇信息.病历号'.", repo.孕妇信息.病历号Info, new RecordItemIndex(4));
            repo.孕妇信息.病历号.Element.SetAttributeValue("Value", "BLH00001");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '孕妇信息.高级搜索按钮' at Center.", repo.孕妇信息.高级搜索按钮Info, new RecordItemIndex(5));
            repo.孕妇信息.高级搜索按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(6));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '(null)' on item '孕妇信息.病历号'.", repo.孕妇信息.病历号Info, new RecordItemIndex(7));
            repo.孕妇信息.病历号.Element.SetAttributeValue("Value", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '钱孕妇' on item '孕妇信息.孕妇姓名'.", repo.孕妇信息.孕妇姓名Info, new RecordItemIndex(8));
            repo.孕妇信息.孕妇姓名.Element.SetAttributeValue("Value", "钱孕妇");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '孕妇信息.高级搜索按钮' at Center.", repo.孕妇信息.高级搜索按钮Info, new RecordItemIndex(9));
            repo.孕妇信息.高级搜索按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(10));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '(null)' on item '孕妇信息.孕妇姓名'.", repo.孕妇信息.孕妇姓名Info, new RecordItemIndex(11));
            repo.孕妇信息.孕妇姓名.Element.SetAttributeValue("Value", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '00003' on item '孕妇信息.社保卡号'.", repo.孕妇信息.社保卡号Info, new RecordItemIndex(12));
            repo.孕妇信息.社保卡号.Element.SetAttributeValue("Value", "00003");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '孕妇信息.高级搜索按钮' at Center.", repo.孕妇信息.高级搜索按钮Info, new RecordItemIndex(13));
            repo.孕妇信息.高级搜索按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(14));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '(null)' on item '孕妇信息.社保卡号'.", repo.孕妇信息.社保卡号Info, new RecordItemIndex(15));
            repo.孕妇信息.社保卡号.Element.SetAttributeValue("Value", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to 'MOZ00004' on item '孕妇信息.筛查号'.", repo.孕妇信息.筛查号Info, new RecordItemIndex(16));
            repo.孕妇信息.筛查号.Element.SetAttributeValue("Value", "MOZ00004");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '孕妇信息.高级搜索按钮' at Center.", repo.孕妇信息.高级搜索按钮Info, new RecordItemIndex(17));
            repo.孕妇信息.高级搜索按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(18));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '(null)' on item '孕妇信息.筛查号'.", repo.孕妇信息.筛查号Info, new RecordItemIndex(19));
            repo.孕妇信息.筛查号.Element.SetAttributeValue("Value", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '5' on item '孕妇信息.人种'.", repo.孕妇信息.人种Info, new RecordItemIndex(20));
            repo.孕妇信息.人种.Element.SetAttributeValue("TagValue", "5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '孕妇信息.高级搜索按钮' at Center.", repo.孕妇信息.高级搜索按钮Info, new RecordItemIndex(21));
            repo.孕妇信息.高级搜索按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(22));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '(null)' on item '孕妇信息.人种'.", repo.孕妇信息.人种Info, new RecordItemIndex(23));
            repo.孕妇信息.人种.Element.SetAttributeValue("TagValue", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '13000000006' on item '孕妇信息.联系电话'.", repo.孕妇信息.联系电话Info, new RecordItemIndex(24));
            repo.孕妇信息.联系电话.Element.SetAttributeValue("Value", "13000000006");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '孕妇信息.高级搜索按钮' at Center.", repo.孕妇信息.高级搜索按钮Info, new RecordItemIndex(25));
            repo.孕妇信息.高级搜索按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(26));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '(null)' on item '孕妇信息.联系电话'.", repo.孕妇信息.联系电话Info, new RecordItemIndex(27));
            repo.孕妇信息.联系电话.Element.SetAttributeValue("Value", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '2018-10-06' on item '孕妇信息.登记开始日期'.", repo.孕妇信息.登记开始日期Info, new RecordItemIndex(28));
            repo.孕妇信息.登记开始日期.Element.SetAttributeValue("Value", "2018-10-06");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '2018-10-07' on item '孕妇信息.登记结束日期'.", repo.孕妇信息.登记结束日期Info, new RecordItemIndex(29));
            repo.孕妇信息.登记结束日期.Element.SetAttributeValue("Value", "2018-10-07");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '孕妇信息.高级搜索按钮' at Center.", repo.孕妇信息.高级搜索按钮Info, new RecordItemIndex(30));
            repo.孕妇信息.高级搜索按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(31));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '(null)' on item '孕妇信息.登记开始日期'.", repo.孕妇信息.登记开始日期Info, new RecordItemIndex(32));
            repo.孕妇信息.登记开始日期.Element.SetAttributeValue("Value", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '(null)' on item '孕妇信息.登记结束日期'.", repo.孕妇信息.登记结束日期Info, new RecordItemIndex(33));
            repo.孕妇信息.登记结束日期.Element.SetAttributeValue("Value", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '孕妇' on item '孕妇信息.孕妇姓名'.", repo.孕妇信息.孕妇姓名Info, new RecordItemIndex(34));
            repo.孕妇信息.孕妇姓名.Element.SetAttributeValue("Value", "孕妇");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '孕妇信息.高级搜索按钮' at Center.", repo.孕妇信息.高级搜索按钮Info, new RecordItemIndex(35));
            repo.孕妇信息.高级搜索按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(36));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '孕妇信息.模板保存' at Center.", repo.孕妇信息.模板保存Info, new RecordItemIndex(37));
            repo.孕妇信息.模板保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '模板一' on item '孕妇信息.模板名称'.", repo.孕妇信息.模板名称Info, new RecordItemIndex(38));
            repo.孕妇信息.模板名称.Element.SetAttributeValue("Value", "模板一");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '孕妇信息.模板保存确认' at Center.", repo.孕妇信息.模板保存确认Info, new RecordItemIndex(39));
            repo.孕妇信息.模板保存确认.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(40));
            Delay.Duration(300, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
