///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MPNS_TEST.Models.Screening_Management.batchCalculate
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The batchCalculate011 recording.
    /// </summary>
    [TestModule("0ac6833c-6451-4311-9bbf-14957f87dbfc", ModuleType.Recording, 1)]
    public partial class batchCalculate011 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MPNS_TEST.Repositorys.Infomation repository.
        /// </summary>
        public static global::MPNS_TEST.Repositorys.Infomation repo = global::MPNS_TEST.Repositorys.Infomation.Instance;

        static batchCalculate011 instance = new batchCalculate011();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public batchCalculate011()
        {
            已生成风险方案 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static batchCalculate011 Instance
        {
            get { return instance; }
        }

#region Variables

        string _已生成风险方案;

        /// <summary>
        /// Gets or sets the value of variable 已生成风险方案.
        /// </summary>
        [TestVariable("eb053db8-9e41-4b08-b7a8-89171495d2a9")]
        public string 已生成风险方案
        {
            get { return _已生成风险方案; }
            set { _已生成风险方案 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.维护管理' at Center.", repo.页面头选择.维护管理Info, new RecordItemIndex(0));
            repo.页面头选择.维护管理.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.参数信息' at Center.", repo.页面头选择.参数信息Info, new RecordItemIndex(1));
            repo.页面头选择.参数信息.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '维护管理批量录入.批量录入' at Center.", repo.维护管理批量录入.批量录入Info, new RecordItemIndex(2));
            repo.维护管理批量录入.批量录入.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Checked' from item '维护管理批量录入.是否包含已生成风险的方案' and assigning its value to variable '已生成风险方案'.", repo.维护管理批量录入.是否包含已生成风险的方案Info, new RecordItemIndex(3));
            已生成风险方案 = repo.维护管理批量录入.是否包含已生成风险的方案.Element.GetAttributeValueText("Checked");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", 已生成风险方案, new RecordItemIndex(4));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
