///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MPNS_TEST.Models.Screening_Management.batchCalculate
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The batchCalculate012 recording.
    /// </summary>
    [TestModule("51b1b01d-4ed7-49dd-a3b5-11b2404b4078", ModuleType.Recording, 1)]
    public partial class BatchCalculate012 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MPNS_TEST.Repositorys.Infomation repository.
        /// </summary>
        public static global::MPNS_TEST.Repositorys.Infomation repo = global::MPNS_TEST.Repositorys.Infomation.Instance;

        static BatchCalculate012 instance = new BatchCalculate012();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BatchCalculate012()
        {
            从仪器获取标记物 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BatchCalculate012 Instance
        {
            get { return instance; }
        }

#region Variables

        string _从仪器获取标记物;

        /// <summary>
        /// Gets or sets the value of variable 从仪器获取标记物.
        /// </summary>
        [TestVariable("492fd7f6-15f2-4633-a18d-3b222cdda221")]
        public string 从仪器获取标记物
        {
            get { return _从仪器获取标记物; }
            set { _从仪器获取标记物 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.维护管理' at Center.", repo.页面头选择.维护管理Info, new RecordItemIndex(0));
            repo.页面头选择.维护管理.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.参数信息' at Center.", repo.页面头选择.参数信息Info, new RecordItemIndex(1));
            repo.页面头选择.参数信息.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '维护管理批量录入.批量录入' at Center.", repo.维护管理批量录入.批量录入Info, new RecordItemIndex(2));
            repo.维护管理批量录入.批量录入.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Checked' from item '维护管理批量录入.是否重新从仪器获取标记物数据' and assigning its value to variable '从仪器获取标记物'.", repo.维护管理批量录入.是否重新从仪器获取标记物数据Info, new RecordItemIndex(3));
            从仪器获取标记物 = repo.维护管理批量录入.是否重新从仪器获取标记物数据.Element.GetAttributeValueText("Checked");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", 从仪器获取标记物, new RecordItemIndex(4));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
