///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MPNS_TEST.Models.Screening_Management.batchInput
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The batchInput004 recording.
    /// </summary>
    [TestModule("7b52a185-cf77-445c-985a-2fa2b7ab5c9f", ModuleType.Recording, 1)]
    public partial class batchInput004 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MPNS_TEST.Repositorys.Infomation repository.
        /// </summary>
        public static global::MPNS_TEST.Repositorys.Infomation repo = global::MPNS_TEST.Repositorys.Infomation.Instance;

        static batchInput004 instance = new batchInput004();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public batchInput004()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static batchInput004 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.维护管理' at Center.", repo.页面头选择.维护管理Info, new RecordItemIndex(0));
            repo.页面头选择.维护管理.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.参数信息' at Center.", repo.页面头选择.参数信息Info, new RecordItemIndex(1));
            repo.页面头选择.参数信息.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(2));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '维护管理批量录入.批量录入' at Center.", repo.维护管理批量录入.批量录入Info, new RecordItemIndex(3));
            repo.维护管理批量录入.批量录入.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Checked to 'true' on item '维护管理批量录入.是否启用默认设置'.", repo.维护管理批量录入.是否启用默认设置Info, new RecordItemIndex(4));
            repo.维护管理批量录入.是否启用默认设置.Element.SetAttributeValue("Checked", "true");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '16' on item '维护管理批量录入.联合评估方法'.", repo.维护管理批量录入.联合评估方法Info, new RecordItemIndex(5));
            repo.维护管理批量录入.联合评估方法.Element.SetAttributeValue("TagValue", "16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '4' on item '维护管理批量录入.中期估方法'.", repo.维护管理批量录入.中期估方法Info, new RecordItemIndex(6));
            repo.维护管理批量录入.中期估方法.Element.SetAttributeValue("TagValue", "4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '10' on item '维护管理批量录入.早期评估方法'.", repo.维护管理批量录入.早期评估方法Info, new RecordItemIndex(7));
            repo.维护管理批量录入.早期评估方法.Element.SetAttributeValue("TagValue", "10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '维护管理批量录入.保存' at Center.", repo.维护管理批量录入.保存Info, new RecordItemIndex(8));
            repo.维护管理批量录入.保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(9));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(10));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(11));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.筛查管理' at Center.", repo.页面头选择.筛查管理Info, new RecordItemIndex(12));
            repo.页面头选择.筛查管理.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.汇总信息' at Center.", repo.页面头选择.汇总信息Info, new RecordItemIndex(13));
            repo.页面头选择.汇总信息.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(14));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '汇总信息.全选框' at Center.", repo.汇总信息.全选框Info, new RecordItemIndex(15));
            repo.汇总信息.全选框.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '汇总信息.撤销审核' at Center.", repo.汇总信息.撤销审核Info, new RecordItemIndex(16));
            repo.汇总信息.撤销审核.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '汇总信息.确定' at Center.", repo.汇总信息.确定Info, new RecordItemIndex(17));
            repo.汇总信息.确定.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(18));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on '登录信息'.", repo.登录信息.SelfInfo, new RecordItemIndex(19));
            repo.登录信息.Self.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '汇总信息.全选框' at Center.", repo.汇总信息.全选框Info, new RecordItemIndex(20));
            repo.汇总信息.全选框.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '汇总信息.删除' at Center.", repo.汇总信息.删除Info, new RecordItemIndex(21));
            repo.汇总信息.删除.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '汇总信息.确定' at Center.", repo.汇总信息.确定Info, new RecordItemIndex(22));
            repo.汇总信息.确定.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(23));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on '登录信息'.", repo.登录信息.SelfInfo, new RecordItemIndex(24));
            repo.登录信息.Self.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(25));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.筛查管理' at Center.", repo.页面头选择.筛查管理Info, new RecordItemIndex(26));
            repo.页面头选择.筛查管理.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.孕妇信息' at Center.", repo.页面头选择.孕妇信息Info, new RecordItemIndex(27));
            repo.页面头选择.孕妇信息.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(28));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '孕妇信息.全选框' at Center.", repo.孕妇信息.全选框Info, new RecordItemIndex(29));
            repo.孕妇信息.全选框.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '孕妇信息.删除' at Center.", repo.孕妇信息.删除Info, new RecordItemIndex(30));
            repo.孕妇信息.删除.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '孕妇信息.确定' at Center.", repo.孕妇信息.确定Info, new RecordItemIndex(31));
            repo.孕妇信息.确定.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(32));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on '登录信息'.", repo.登录信息.SelfInfo, new RecordItemIndex(33));
            repo.登录信息.Self.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(34));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.筛查管理' at Center.", repo.页面头选择.筛查管理Info, new RecordItemIndex(35));
            repo.页面头选择.筛查管理.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.批量录入' at Center.", repo.页面头选择.批量录入Info, new RecordItemIndex(36));
            repo.页面头选择.批量录入.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(37));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '2017-10-11' on item '筛查管理批量录入.开始日期'.", repo.筛查管理批量录入.开始日期Info, new RecordItemIndex(38));
            repo.筛查管理批量录入.开始日期.Element.SetAttributeValue("Value", "2017-10-11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '2020-10-12' on item '筛查管理批量录入.结束日期'.", repo.筛查管理批量录入.结束日期Info, new RecordItemIndex(39));
            repo.筛查管理批量录入.结束日期.Element.SetAttributeValue("Value", "2020-10-12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查管理批量录入.外部查询' at Center.", repo.筛查管理批量录入.外部查询Info, new RecordItemIndex(40));
            repo.筛查管理批量录入.外部查询.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(41));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查管理批量录入.全选框' at Center.", repo.筛查管理批量录入.全选框Info, new RecordItemIndex(42));
            repo.筛查管理批量录入.全选框.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查管理批量录入.保存' at Center.", repo.筛查管理批量录入.保存Info, new RecordItemIndex(43));
            repo.筛查管理批量录入.保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(44));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查管理批量录入.确定导入' at Center.", repo.筛查管理批量录入.确定导入Info, new RecordItemIndex(45));
            repo.筛查管理批量录入.确定导入.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
