///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MPNS_TEST.Models.Screening_Management.revisit
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The revisit033 recording.
    /// </summary>
    [TestModule("7c0edb4d-64f3-4874-a9b1-7262bc8cb95c", ModuleType.Recording, 1)]
    public partial class revisit033 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MPNS_TEST.Repositorys.Infomation repository.
        /// </summary>
        public static global::MPNS_TEST.Repositorys.Infomation repo = global::MPNS_TEST.Repositorys.Infomation.Instance;

        static revisit033 instance = new revisit033();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public revisit033()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static revisit033 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.基础信息管理' at Center.", repo.页面头选择.基础信息管理Info, new RecordItemIndex(0));
            repo.页面头选择.基础信息管理.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.医院医生' at Center.", repo.页面头选择.医院医生Info, new RecordItemIndex(1));
            repo.页面头选择.医院医生.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '医院医生.新增医生' at Center.", repo.医院医生.新增医生Info, new RecordItemIndex(2));
            repo.医院医生.新增医生.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(3));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '医院医生.新增医生' at Center.", repo.医院医生.新增医生Info, new RecordItemIndex(4));
            repo.医院医生.新增医生.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '新华医院' on item '医院医生.来源单位'.", repo.医院医生.来源单位Info, new RecordItemIndex(5));
            repo.医院医生.来源单位.Element.SetAttributeValue("Value", "新华医院");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '张医生' on item '医院医生.送检医生'.", repo.医院医生.送检医生Info, new RecordItemIndex(6));
            repo.医院医生.送检医生.Element.SetAttributeValue("Value", "张医生");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '医院医生.保存' at Center.", repo.医院医生.保存Info, new RecordItemIndex(7));
            repo.医院医生.保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '医院医生.确定' at Center.", repo.医院医生.确定Info, new RecordItemIndex(8));
            repo.医院医生.确定.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '医院医生.新增医生' at Center.", repo.医院医生.新增医生Info, new RecordItemIndex(9));
            repo.医院医生.新增医生.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(10));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '华山医院' on item '医院医生.来源单位'.", repo.医院医生.来源单位Info, new RecordItemIndex(11));
            repo.医院医生.来源单位.Element.SetAttributeValue("Value", "华山医院");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '李医生' on item '医院医生.送检医生'.", repo.医院医生.送检医生Info, new RecordItemIndex(12));
            repo.医院医生.送检医生.Element.SetAttributeValue("Value", "李医生");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '医院医生.保存' at Center.", repo.医院医生.保存Info, new RecordItemIndex(13));
            repo.医院医生.保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '医院医生.确定' at Center.", repo.医院医生.确定Info, new RecordItemIndex(14));
            repo.医院医生.确定.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.筛查管理' at Center.", repo.页面头选择.筛查管理Info, new RecordItemIndex(15));
            repo.页面头选择.筛查管理.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.筛查回访' at Center.", repo.页面头选择.筛查回访Info, new RecordItemIndex(16));
            repo.页面头选择.筛查回访.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(17));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '冯孕妇007' on item '筛查回访.搜索框内容'.", repo.筛查回访.搜索框内容Info, new RecordItemIndex(18));
            repo.筛查回访.搜索框内容.Element.SetAttributeValue("Value", "冯孕妇007");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查回访.点击搜索' at Center.", repo.筛查回访.点击搜索Info, new RecordItemIndex(19));
            repo.筛查回访.点击搜索.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查回访.第一个回访对象' at Center.", repo.筛查回访.第一个回访对象Info, new RecordItemIndex(20));
            repo.筛查回访.第一个回访对象.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查回访.分娩信息' at Center.", repo.筛查回访.分娩信息Info, new RecordItemIndex(21));
            repo.筛查回访.分娩信息.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '' on item '筛查回访.生产医院'.", repo.筛查回访.生产医院Info, new RecordItemIndex(22));
            repo.筛查回访.生产医院.Element.SetAttributeValue("TagValue", "");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查回访.分娩信息回访保存' at Center.", repo.筛查回访.分娩信息回访保存Info, new RecordItemIndex(23));
            repo.筛查回访.分娩信息回访保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(24));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(25));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
