///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MPNS_TEST.Models.Screening_Management.revisit
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The revisit055 recording.
    /// </summary>
    [TestModule("c451d663-7716-4ccf-8ce6-0115a21db955", ModuleType.Recording, 1)]
    public partial class revisit055 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MPNS_TEST.Repositorys.Infomation repository.
        /// </summary>
        public static global::MPNS_TEST.Repositorys.Infomation repo = global::MPNS_TEST.Repositorys.Infomation.Instance;

        static revisit055 instance = new revisit055();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public revisit055()
        {
            备注信息 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static revisit055 Instance
        {
            get { return instance; }
        }

#region Variables

        string _备注信息;

        /// <summary>
        /// Gets or sets the value of variable 备注信息.
        /// </summary>
        [TestVariable("debdce1f-7801-4297-9a09-ecbe9a1edd32")]
        public string 备注信息
        {
            get { return _备注信息; }
            set { _备注信息 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item '筛查回访.新生儿信息备注' and assigning its value to variable '备注信息'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(0));
            备注信息 = repo.筛查回访.新生儿信息备注.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", 备注信息, new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '(null)' on item '筛查回访.新生儿信息备注'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(2));
            repo.筛查回访.新生儿信息备注.Element.SetAttributeValue("TagValue", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' with focus on '筛查回访.新生儿信息备注'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(3));
            repo.筛查回访.新生儿信息备注.PressKeys("12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' with focus on '筛查回访.新生儿信息备注'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(4));
            repo.筛查回访.新生儿信息备注.PressKeys("12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' with focus on '筛查回访.新生儿信息备注'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(5));
            repo.筛查回访.新生儿信息备注.PressKeys("12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' with focus on '筛查回访.新生儿信息备注'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(6));
            repo.筛查回访.新生儿信息备注.PressKeys("12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' with focus on '筛查回访.新生儿信息备注'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(7));
            repo.筛查回访.新生儿信息备注.PressKeys("12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '123456789012345678901234' with focus on '筛查回访.新生儿信息备注'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(8));
            repo.筛查回访.新生儿信息备注.PressKeys("123456789012345678901234");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查回访.新生儿信息保存' at Center.", repo.筛查回访.新生儿信息保存Info, new RecordItemIndex(9));
            repo.筛查回访.新生儿信息保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(10));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(11));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '(null)' on item '筛查回访.新生儿信息备注'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(12));
            repo.筛查回访.新生儿信息备注.Element.SetAttributeValue("TagValue", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' with focus on '筛查回访.新生儿信息备注'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(13));
            repo.筛查回访.新生儿信息备注.PressKeys("12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' with focus on '筛查回访.新生儿信息备注'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(14));
            repo.筛查回访.新生儿信息备注.PressKeys("12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' with focus on '筛查回访.新生儿信息备注'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(15));
            repo.筛查回访.新生儿信息备注.PressKeys("12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' with focus on '筛查回访.新生儿信息备注'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(16));
            repo.筛查回访.新生儿信息备注.PressKeys("12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' with focus on '筛查回访.新生儿信息备注'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(17));
            repo.筛查回访.新生儿信息备注.PressKeys("12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1234567890123456789012345' with focus on '筛查回访.新生儿信息备注'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(18));
            repo.筛查回访.新生儿信息备注.PressKeys("1234567890123456789012345");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查回访.新生儿信息保存' at Center.", repo.筛查回访.新生儿信息保存Info, new RecordItemIndex(19));
            repo.筛查回访.新生儿信息保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(20));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(21));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '(null)' on item '筛查回访.新生儿信息备注'.", repo.筛查回访.新生儿信息备注Info, new RecordItemIndex(22));
            repo.筛查回访.新生儿信息备注.Element.SetAttributeValue("TagValue", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查回访.新生儿信息保存' at Center.", repo.筛查回访.新生儿信息保存Info, new RecordItemIndex(23));
            repo.筛查回访.新生儿信息保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(24));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(25));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
