///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MPNS_TEST.Models.Screening_Management.revisit
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The revisit035 recording.
    /// </summary>
    [TestModule("badc5027-9c51-47fb-be23-53066b03022f", ModuleType.Recording, 1)]
    public partial class revisit035 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MPNS_TEST.Repositorys.Infomation repository.
        /// </summary>
        public static global::MPNS_TEST.Repositorys.Infomation repo = global::MPNS_TEST.Repositorys.Infomation.Instance;

        static revisit035 instance = new revisit035();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public revisit035()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static revisit035 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '99' on item '筛查回访.孕周数周'.", repo.筛查回访.孕周数周Info, new RecordItemIndex(0));
            repo.筛查回访.孕周数周.Element.SetAttributeValue("Value", "99");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '0' on item '筛查回访.孕周数天'.", repo.筛查回访.孕周数天Info, new RecordItemIndex(1));
            repo.筛查回访.孕周数天.Element.SetAttributeValue("Value", "0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查回访.分娩信息回访保存' at Center.", repo.筛查回访.分娩信息回访保存Info, new RecordItemIndex(2));
            repo.筛查回访.分娩信息回访保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(3));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(4));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '0' on item '筛查回访.孕周数周'.", repo.筛查回访.孕周数周Info, new RecordItemIndex(5));
            repo.筛查回访.孕周数周.Element.SetAttributeValue("Value", "0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '0' on item '筛查回访.孕周数天'.", repo.筛查回访.孕周数天Info, new RecordItemIndex(6));
            repo.筛查回访.孕周数天.Element.SetAttributeValue("Value", "0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查回访.分娩信息回访保存' at Center.", repo.筛查回访.分娩信息回访保存Info, new RecordItemIndex(7));
            repo.筛查回访.分娩信息回访保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(8));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(9));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '(null)' on item '筛查回访.孕周数周'.", repo.筛查回访.孕周数周Info, new RecordItemIndex(10));
            repo.筛查回访.孕周数周.Element.SetAttributeValue("Value", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '0' on item '筛查回访.孕周数天'.", repo.筛查回访.孕周数天Info, new RecordItemIndex(11));
            repo.筛查回访.孕周数天.Element.SetAttributeValue("Value", "0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查回访.分娩信息回访保存' at Center.", repo.筛查回访.分娩信息回访保存Info, new RecordItemIndex(12));
            repo.筛查回访.分娩信息回访保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(13));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(14));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '1.5' on item '筛查回访.孕周数周'.", repo.筛查回访.孕周数周Info, new RecordItemIndex(15));
            repo.筛查回访.孕周数周.Element.SetAttributeValue("Value", "1.5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '0' on item '筛查回访.孕周数天'.", repo.筛查回访.孕周数天Info, new RecordItemIndex(16));
            repo.筛查回访.孕周数天.Element.SetAttributeValue("Value", "0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查回访.分娩信息回访保存' at Center.", repo.筛查回访.分娩信息回访保存Info, new RecordItemIndex(17));
            repo.筛查回访.分娩信息回访保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(18));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(19));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to 'a' on item '筛查回访.孕周数周'.", repo.筛查回访.孕周数周Info, new RecordItemIndex(20));
            repo.筛查回访.孕周数周.Element.SetAttributeValue("Value", "a");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '0' on item '筛查回访.孕周数天'.", repo.筛查回访.孕周数天Info, new RecordItemIndex(21));
            repo.筛查回访.孕周数天.Element.SetAttributeValue("Value", "0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查回访.分娩信息回访保存' at Center.", repo.筛查回访.分娩信息回访保存Info, new RecordItemIndex(22));
            repo.筛查回访.分娩信息回访保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(23));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(24));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '-1' on item '筛查回访.孕周数周'.", repo.筛查回访.孕周数周Info, new RecordItemIndex(25));
            repo.筛查回访.孕周数周.Element.SetAttributeValue("Value", "-1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '0' on item '筛查回访.孕周数天'.", repo.筛查回访.孕周数天Info, new RecordItemIndex(26));
            repo.筛查回访.孕周数天.Element.SetAttributeValue("Value", "0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查回访.分娩信息回访保存' at Center.", repo.筛查回访.分娩信息回访保存Info, new RecordItemIndex(27));
            repo.筛查回访.分娩信息回访保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(28));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(29));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '100' on item '筛查回访.孕周数周'.", repo.筛查回访.孕周数周Info, new RecordItemIndex(30));
            repo.筛查回访.孕周数周.Element.SetAttributeValue("Value", "100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '0' on item '筛查回访.孕周数天'.", repo.筛查回访.孕周数天Info, new RecordItemIndex(31));
            repo.筛查回访.孕周数天.Element.SetAttributeValue("Value", "0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查回访.分娩信息回访保存' at Center.", repo.筛查回访.分娩信息回访保存Info, new RecordItemIndex(32));
            repo.筛查回访.分娩信息回访保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(33));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(34));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
