///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MPNS_TEST.Models.Screening_Management.sample
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The sample022 recording.
    /// </summary>
    [TestModule("a23b1512-b8fd-460e-9050-4dd3261a2643", ModuleType.Recording, 1)]
    public partial class sample022 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MPNS_TEST.Repositorys.Infomation repository.
        /// </summary>
        public static global::MPNS_TEST.Repositorys.Infomation repo = global::MPNS_TEST.Repositorys.Infomation.Instance;

        static sample022 instance = new sample022();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public sample022()
        {
            早期测试日期 = "";
            中期测试日期 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static sample022 Instance
        {
            get { return instance; }
        }

#region Variables

        string _早期测试日期;

        /// <summary>
        /// Gets or sets the value of variable 早期测试日期.
        /// </summary>
        [TestVariable("36bd55ab-6540-4bc7-be9c-ad512154c7e4")]
        public string 早期测试日期
        {
            get { return _早期测试日期; }
            set { _早期测试日期 = value; }
        }

        string _中期测试日期;

        /// <summary>
        /// Gets or sets the value of variable 中期测试日期.
        /// </summary>
        [TestVariable("4ce95eba-28b7-4a34-b6a7-b29dd3e31e4a")]
        public string 中期测试日期
        {
            get { return _中期测试日期; }
            set { _中期测试日期 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.筛查管理' at Center.", repo.页面头选择.筛查管理Info, new RecordItemIndex(0));
            repo.页面头选择.筛查管理.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '页面头选择.筛查信息' at Center.", repo.页面头选择.筛查信息Info, new RecordItemIndex(1));
            repo.页面头选择.筛查信息.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(2));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '周孕妇022' on item '筛查信息.孕妇姓名'.", repo.筛查信息.孕妇姓名Info, new RecordItemIndex(3));
            repo.筛查信息.孕妇姓名.Element.SetAttributeValue("Value", "周孕妇022");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '1990-01-01' on item '筛查信息.出生日期'.", repo.筛查信息.出生日期Info, new RecordItemIndex(4));
            repo.筛查信息.出生日期.Element.SetAttributeValue("Value", "1990-01-01");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '筛查信息.保存按钮' at Center.", repo.筛查信息.保存按钮Info, new RecordItemIndex(5));
            repo.筛查信息.保存按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '早期样本.新增早期样本' at Center.", repo.早期样本.新增早期样本Info, new RecordItemIndex(7));
            repo.早期样本.新增早期样本.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '12345678901234567890' with focus on '早期样本.早期样本号'.", repo.早期样本.早期样本号Info, new RecordItemIndex(8));
            repo.早期样本.早期样本号.PressKeys("12345678901234567890");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Value' from item '早期样本.测试日期' and assigning its value to variable '早期测试日期'.", repo.早期样本.测试日期Info, new RecordItemIndex(9));
            早期测试日期 = repo.早期样本.测试日期.Element.GetAttributeValueText("Value");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", 早期测试日期, new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '早期样本.CRL日期' at Center.", repo.早期样本.CRL日期Info, new RecordItemIndex(11));
            repo.早期样本.CRL日期.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '早期样本.CRL日期选择今天' at Center.", repo.早期样本.CRL日期选择今天Info, new RecordItemIndex(12));
            repo.早期样本.CRL日期选择今天.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '43' on item '早期样本.CRL长度'.", repo.早期样本.CRL长度Info, new RecordItemIndex(13));
            repo.早期样本.CRL长度.Element.SetAttributeValue("Value", "43");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '早期样本.计算按钮' at Center.", repo.早期样本.计算按钮Info, new RecordItemIndex(14));
            repo.早期样本.计算按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '45' on item '早期样本.体重'.", repo.早期样本.体重Info, new RecordItemIndex(15));
            repo.早期样本.体重.Element.SetAttributeValue("Value", "45");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '早期样本.保存按钮' at Center.", repo.早期样本.保存按钮Info, new RecordItemIndex(16));
            repo.早期样本.保存按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '(null)' on item '早期样本.测试日期'.", repo.早期样本.测试日期Info, new RecordItemIndex(17));
            repo.早期样本.测试日期.Element.SetAttributeValue("Value", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '早期样本.保存按钮' at Center.", repo.早期样本.保存按钮Info, new RecordItemIndex(18));
            repo.早期样本.保存按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(19));
            Delay.Duration(300, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.早期样本.采样日期不能为空, false, new RecordItemIndex(20));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(21));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '早期样本.确认测试日期' at Center.", repo.早期样本.确认测试日期Info, new RecordItemIndex(22));
            repo.早期样本.确认测试日期.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(23));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '早期样本.删除按钮' at Center.", repo.早期样本.删除按钮Info, new RecordItemIndex(24));
            repo.早期样本.删除按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(25));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on '早期样本'.", repo.早期样本.SelfInfo, new RecordItemIndex(26));
            repo.早期样本.Self.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '中期样本.新增中期样本' at Center.", repo.中期样本.新增中期样本Info, new RecordItemIndex(27));
            repo.中期样本.新增中期样本.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(28));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '34234237832984' on item '中期样本.中期样本号'.", repo.中期样本.中期样本号Info, new RecordItemIndex(29));
            repo.中期样本.中期样本号.Element.SetAttributeValue("Value", "34234237832984");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '50' on item '中期样本.体重'.", repo.中期样本.体重Info, new RecordItemIndex(30));
            repo.中期样本.体重.Element.SetAttributeValue("Value", "50");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Value' from item '中期样本.测试日期' and assigning its value to variable '中期测试日期'.", repo.中期样本.测试日期Info, new RecordItemIndex(31));
            中期测试日期 = repo.中期样本.测试日期.Element.GetAttributeValueText("Value");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", 中期测试日期, new RecordItemIndex(32));
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$中期测试日期' on item '中期样本.BPD日期'.", repo.中期样本.BPD日期Info, new RecordItemIndex(33));
            repo.中期样本.BPD日期.Element.SetAttributeValue("Value", 中期测试日期);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '45' on item '中期样本.BPD长度'.", repo.中期样本.BPD长度Info, new RecordItemIndex(34));
            repo.中期样本.BPD长度.Element.SetAttributeValue("Value", "45");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '中期样本.计算按钮' at Center.", repo.中期样本.计算按钮Info, new RecordItemIndex(35));
            repo.中期样本.计算按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(36));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '中期样本.保存按钮' at Center.", repo.中期样本.保存按钮Info, new RecordItemIndex(37));
            repo.中期样本.保存按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(38));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '(null)' on item '中期样本.测试日期'.", repo.中期样本.测试日期Info, new RecordItemIndex(39));
            repo.中期样本.测试日期.Element.SetAttributeValue("Value", null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '中期样本.保存按钮' at Center.", repo.中期样本.保存按钮Info, new RecordItemIndex(40));
            repo.中期样本.保存按钮.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(41));
            Delay.Duration(300, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.中期样本.测试日期不能为空, false, new RecordItemIndex(42));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '中期样本.确认测试日期' at Center.", repo.中期样本.确认测试日期Info, new RecordItemIndex(43));
            repo.中期样本.确认测试日期.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
